import type { Metadata } from "next";
import "./globals.css";
import Navbar from "./components/Navbar";
//import Footer from "./components/Footer";

export const metadata: Metadata = {
  title: "Etemdrop",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className="bg-[#181818]">
        <Navbar />
        {children}
      </body>
    </html>
  );
}
